#!/usr/bin/env bun
/**
 * Build the context string to inject into Claude's prompt.
 * Only injects the requirement-doc README.md if it exists.
 */

import type { WorktreeInfo } from "./detect-worktree";
import type { MemoryResult } from "./query-memory";

/**
 * Build the full context string
 */
export function buildContext(worktree: WorktreeInfo, memory: MemoryResult): string {
  const parts: string[] = [];

  // Inject requirement doc if present
  if (memory.requirementDoc) {
    parts.push("<worktree-requirement-doc>");
    parts.push("");
    parts.push(`<!-- Source: ${memory.requirementDoc.path} -->`);
    parts.push("");
    parts.push(memory.requirementDoc.content);
    parts.push("");
    parts.push("</worktree-requirement-doc>");
  }

  // Inject superpower docs location rule (always)
  parts.push("<worktree-convention>");
  parts.push("");
  parts.push("Superpower (writing-plans, brainstorming, etc.) generated docs must be placed at:");
  parts.push(`  {worktree_root}/requirement-docs/{worktree-name}/README.md (or PLAN.md, design.md)`);
  parts.push("Priority: README.md > PLAN.md > design.md");
  parts.push("Current worktree: " + (worktree.branch || worktree.cwd));
  parts.push("");
  parts.push("When executing plans generated by superpower skills, prefer Parallel Agent execution (subagent-driven) over inline execution.");
  parts.push("Dispatch independent tasks to separate subagents concurrently rather than executing sequentially in the main session.");
  parts.push("");
  parts.push("</worktree-convention>");

  return parts.join("\n");
}

// CLI entry point for testing
if (import.meta.main) {
  const { detectWorktree } = await import("./detect-worktree");
  const { queryMemory } = await import("./query-memory");

  const worktree = await detectWorktree(process.cwd());

  if (worktree) {
    const memory = await queryMemory(worktree);
    const context = buildContext(worktree, memory);
    if (context) {
      console.log(context);
    } else {
      console.log("No requirement doc to inject");
    }
  } else {
    console.log("Not in a worktree-manager workspace");
  }
}
